# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net
name: 1.$(Rev:r)

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Compile
  jobs:
  - job: Initialize
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
      
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: CopyFiles@2
      displayName: 'Copy artifacts to staging'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)/Release'
        Contents: '*.exe'
        TargetFolder: '$(build.artifactstagingdirectory)'
        
    - task: GitHubRelease@1
      inputs:
        gitHubConnection: 'Github'
        repositoryName: 'Zeracronius/RimworldModManager'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'userSpecifiedTag'
        tag: 'v$(Build.BuildNumber)'
        title: 'v$(Build.BuildNumber)'
        changeLogCompareToRelease: 'lastFullRelease'
        changeLogType: 'commitBased'