# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Compile
  jobs:
  - job: Initialize
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
      
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: CopyFiles@2
      displayName: 'Copy artifacts to staging'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)/Release'
        Contents: '*.exe'
        TargetFolder: '$(build.artifactstagingdirectory)'


        
  - task: PowerShell@2
    displayName: 'Read version no. from primary EXE/AssemblyInfo'
    inputs:
      targetType: 'inline'
      script: |
        # Use reflection to get the assembly version (as defined in AssemblyInfo.cs) from the main assembly:
        $asm = "$(Build.ArtifactStagingDirectory)\ModManager.exe"
        Write-Output "Reading ReleaseVersion from: $asm"
        
        $version = [System.Reflection.AssemblyName]::GetAssemblyName("$asm").Version.ToString(3)
               
        # Update the Build Number to match (this happens when the task completes):
        Write-Host ("##vso[build.updatebuildnumber]$version")
        Write-Output "Build.BuildNumber before: $(Build.BuildNumber)"
        
    - task: GitHubRelease@1
      inputs:
        gitHubConnection: 'Github'
        repositoryName: 'Zeracronius/RimworldModManager'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'userSpecifiedTag'
        tag: 'v$(build.updatebuildnumber)'
        title: 'v$(build.updatebuildnumber)'
        changeLogCompareToRelease: 'lastFullRelease'
        changeLogType: 'commitBased'